# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2828756aad9707792e10253e1b0f4d1dfd74afb2cf669ea0bdef813b29fb92784ef358cc329a13fc01781f1dc48c170f440e0e5ff0bc7c212925f5355cbf8e34

test:
  secret_key_base: 0aad3f5b3086432f62f1eed1c03eb0be2273277b9f193f44d2b9228f33a618d502c83efc0659c82d334cdf4b058ef794aa575fa1b378a07c382f843e41548b85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
